FROM golang:1.22

RUN go mod init github.com/binkynet/u-root-build-image && \
    go install github.com/u-root/u-root@v0.14.0

RUN mkdir -p /go/u-root && cd /go && \
    git clone https://github.com/u-root/u-root
